#!/usr/bin/python3

import pickle
import sys


def convert_bytes_to_bitstring(data_to_decode, endZeroPadding):
    """This function converts bytes into a string of bits.

    Args:
        data_to_decode (str): This is the string of bytes that will be
                              converted into bits.
        endZeroPadding (int): This is the number of zeroes that were
                              padded into the final byte. They will be
                              removed so the resultant bit string can be
                              properly decompressed.

    Returns:
        bitString (str): This is the string of bits that will need to be
                         parsed into hexadecimal pairs that represent
                         the bytes of the decompressed wave file.
    """
    bitString = ""
    for byteIndex in range(0, len(data_to_decode)):
        bitStringByte = format(data_to_decode[byteIndex], "b")
        bitStringByte = "0" * (8 - len(bitStringByte)) + bitStringByte
        bitString += bitStringByte
    bitString = bitString[: len(bitString) - endZeroPadding]
    return bitString


def find_key_by_value_in_node_mapping_dictionary(
    val_str_to_find, nodeMappingDictionary
):
    """This function allows the searching of the nodeMappingDictionary
    for a key given a value.

    Args:
        val_str_to_find (str): This is expected to be a string of bits.
        nodeMappingDictionary (dict): This is the dictionary that maps
                                      hexadecimal values as keys in the
                                      dictionary to uniquely identifying
                                      strings of bits as values.

    Returns:
        key_mapped_to_value (list): This function returns the
                                    hexadecimal pair found as a key in
                                    the nodeMappingDictionary given a
                                    string of bit values. If the given
                                    string of bits is not found in the
                                    dictionary, the return value is
                                    'None'.
    """
    try:
        key_mapped_to_value = list(nodeMappingDictionary.keys())[
            list(nodeMappingDictionary.values()).index(val_str_to_find)
        ]
    except ValueError:
        return None
    return key_mapped_to_value


def huffman_decoding(
    compressed_file_path: str = None, decompressed_file_path: str = None
):
    """The main driving method that will decode a huffman encoded file.

    Args:
        compressed_file_path (str, optional): The path of the compressed
                                              file to decompress.
                                              Defaults to None.
        decompressed_file_path (str, optional): The path of the output
                                                decompressed file.
                                                Defaults to None.
    """

    if compressed_file_path == None:
        compressed_file_path = sys.argv[1]

    if decompressed_file_path == None:
        decompressed_file_path = sys.argv[2]

    # Retrieve the encoded file for decoding and parse the file.
    with open(compressed_file_path, "rb+") as file:
        encoded_data = file.read()
    nodeMappingDictionary = pickle.loads(encoded_data)
    indices_byte_size = encoded_data[len(encoded_data) - 1]
    indices_pickle = encoded_data[
        len(encoded_data) - 1 - indices_byte_size : len(encoded_data) - 1
    ]
    indices_array = pickle.loads(indices_pickle)
    data_to_decode = encoded_data[indices_array[1] : indices_array[2]]
    bitString = convert_bytes_to_bitstring(data_to_decode, indices_array[-1])

    # Parse the string of bits into hexadecimal values.
    hex_value_array = []
    bitLength = 0
    while len(bitString) > 0:
        key = find_key_by_value_in_node_mapping_dictionary(
            bitString[:bitLength], nodeMappingDictionary
        )
        if key is not None:
            hex_value_array.append(key)
            bitString = bitString[bitLength:]
            bitLength = 0
        else:
            bitLength += 1
    hex_wav_str = ""
    hex_wav_str = hex_wav_str.join(hex_value_array)
    decoded_wav_bytes = bytes.fromhex(hex_wav_str)

    with open(decompressed_file_path, "wb+") as f:
        f.write(decoded_wav_bytes)
        f.close()


if __name__ == "__main__":
    huffman_decoding()
